name: Deploy to Azure

on: workflow_dispatch
permissions:
 id-token: write
 contents: read
 
jobs:
 deploy-infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
         
    steps:
    
    # Checkout triggering repo
     - uses: actions/checkout@v4
          
    # az login using SPN
     - name: Login via Azure CLI
       uses: azure/login@v1
       with:
   
        client-id: ${{ secrets.clientID }}
        tenant-id: ${{ secrets.tenantID }}
        subscription-id: ${{ secrets.subscription }} 
        
     - name: Deploy Azure Resource Manager (ARM) Template
       uses: Azure/arm-deploy@v1.0.9
       with:
         scope: 'resourcegroup'
         subscriptionId: ${{ secrets.subscription }} 
         resourceGroupName: 'rg-deployment-target-dev'
         template: .\.\InfrastructureAsCode\main.bicep
         deploymentMode: 'Incremental'
         deploymentName: 'TrainingDeploy'
         parameters: environment=dev
        
               
