name: Deploy to Azure

on: workflow_dispatch
permissions:
 id-token: write
 contents: read
 
jobs:
 deploy-infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
         
    steps:
    
    # Checkout triggering repo
     - uses: actions/checkout@v4
          
    # az login using SPN
     - name: Login via Azure CLI
       uses: azure/login@v1
       with:
   
        client-id: ${{ secrets.clientID }}
        tenant-id: ${{ secrets.tenantID }}
        subscription-id: ${{ secrets.subscription }} 
